# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40ccda1347cf97b44349e054daf47c81212a5b1f4b20d6efe07520496a47631b7b92a40165536c6614659ffaf83e43f909b24082f0f93ed42ab07632a25cf842

test:
  secret_key_base: bab4ab935138fee27ff675686f9cf7eca358a6dbd021bbaa981039a7c754a9cb2b81698f318aea41c1d3a4f4da699cf68b311a82e1d32405825577d1146b6e01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
